user www-data;
worker_processes 1;
error_log stderr;

events {
  worker_connections 1024;
}

http {
  sendfile on;
  tcp_nopush on;
  tcp_nodelay on;
  keepalive_timeout 10;
  add_header "Vary" "Accept-Encoding";
  include /etc/nginx/mime.types;
  default_type application/octet-stream;
  charset utf-8;
  port_in_redirect off;
  server_name_in_redirect off;
  gzip on;
  gzip_http_version 1.0;
  gzip_comp_level 2;
  gzip_min_length 1100;
  gzip_proxied any;
  gzip_static on;
  gzip_types text/plain text/css text/xml application/xml
    application/xml+rss application/x-javascript text/javascript
    application/javascript application/json;

  server {
    listen 0.0.0.0:80;
    server_name _;
    root /usr/share/nginx/html;
    access_log /dev/stdout;

    location = /ping {
      auth_basic off;
      return 200;
    }

    # REMOVEME, legacy
    location = /healthz {
      auth_basic off;
      return 200;
    }

    location = /nginx_status {
      stub_status on;
      access_log off;
      allow 127.0.0.1;
      deny all;
    }

    # Drop legacy URLs to engine monitor
    location /zebra/monitor {
      auth_basic off;
      return 404;
    }
  }
}
