# Defines cert-manager certificate for our hosts.
apiVersion: certmanager.k8s.io/v1alpha1
kind: Certificate
metadata:
  name: {{ .Values.name | quote }}
  labels:
    {{ range $k, $v := .Values.labels }}
    {{ $k }}: {{ $v | quote }}
    {{ end }}
  annotations:
    {{ range $k, $v := .Values.annotations }}
    {{ $k }}: {{ $v | quote }}
    {{ end }}
spec:
  # This will be created by cert-manager
  secretName: {{ .Values.kubernetes.certManagerTLSSecretName | quote }}

  issuerRef:
    # This refers to cert-manager's cluster-wide issuer, which must already exist.
    kind: ClusterIssuer
    name: cert-manager-letsencrypt

  # Domains
  commonName: {{ .Values.settings.domain }}
  dnsNames:
  - www.{{ .Values.settings.domain }}
  - monitor.{{ .Values.settings.domain }}

  acme:
    config:
    - http01:
        # Name of ingress
        ingress: {{ .Values.name }}

      # Domains, repeated here
      domains:
      - {{ .Values.settings.domain }}
      - www.{{ .Values.settings.domain }}
      - monitor.{{ .Values.settings.domain }}
