apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: {{ .Values.name }}
  labels:
    app: transparensee-site
    {{ range $k, $v := .Values.labels }}
    {{ $k }}: "{{ $v }}"
    {{ end }}
  annotations:
    {{ range $k, $v := .Values.annotations }}
    {{ $k }}: "{{ $v }}"
    {{ end }}
spec:
  replicas: {{ .Values.replicas }}
  template:
    metadata:
      labels:
        app: transparensee-site
        {{ range $k, $v := .Values.labels }}
        {{ $k }}: "{{ $v }}"
        {{ end }}
      annotations:
        {{ range $k, $v := .Values.annotations }}
        {{ $k }}: "{{ $v }}"
        {{ end }}
    spec:
      containers:
      - name: transparensee-site
        image: "{{ .Values.image }}:{{ .Values.imageTag }}"
        imagePullPolicy: Always
        ports:
        - containerPort: 80
          protocol: TCP
        readinessProbe:
          httpGet:
            path: /ping
            port: 80
            scheme: HTTP
          initialDelaySeconds: 5
          timeoutSeconds: 5
        resources:
          requests:
            memory: 10Mi
            cpu: 0.01
          limits:
            memory: 10Mi
            cpu: 0.01
      # FIXME: Disabled as it's broken right now, and the author does
      #   not use tags we can roll back to.
      # - name: exporter
      #   image: fish/nginx-exporter
      #   imagePullPolicy: IfNotPresent
      #   ports:
      #   - containerPort: 9113
      #     protocol: TCP
      #   args:
      #   - "-nginx.scrape_uri=http://127.0.0.1/nginx_status"
