apiVersion: networking.gke.io/v1beta1
kind: ManagedCertificate
metadata:
  name: {{ .Values.name }}-monitor.transparensee.com
  labels:
    {{ range $k, $v := .Values.labels }}
    {{ $k }}: {{ $v | quote }}
    {{ end }}
  annotations:
    {{ range $k, $v := .Values.annotations }}
    {{ $k }}: {{ $v | quote }}
    {{ end }}
spec:
  domains:
  - monitor.transparensee.com
