apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.name }}
  labels:
    app: transparensee-site
    {{ range $k, $v := .Values.labels }}
    {{ $k }}: "{{ $v }}"
    {{ end }}
  annotations:
    {{ range $k, $v := .Values.annotations }}
    {{ $k }}: "{{ $v }}"
    {{ end }}
spec:
  selector:
    app: transparensee-site
    {{ range $k, $v := .Values.labels }}
    {{ $k }}: "{{ $v }}"
    {{ end }}
  # Required for GKE ingress LB
  type: NodePort
  ports:
  - name: http
    port: 80
    targetPort: 80
    protocol: TCP
